name: flutterpi_tool
description: A tool to make development & distribution of flutter-pi apps easier.
version: 0.5.4
repository: https://github.com/ardera/flutterpi_tool

environment:
  sdk: ^3.0.5
  flutter: ">=3.22.0"

executables:
  # TODO(ardera): Maybe add an alias `flutterpi-tool` here?
  flutterpi_tool: flutterpi_tool

# Add regular dependencies here.
dependencies:
  flutter_tools:
    sdk: flutter
  package_config: ^2.1.0
  github: ^9.24.0
  file: ">=7.0.0"
  path: ^1.9.0
  args: ^2.5.0
  http: ^1.2.2
  meta: ^1.15.0
  process: ^5.0.2
  unified_analytics: ">=6.1.3"
  archive: ^3.6.1
  crypto: ^3.0.5

dev_dependencies:
  lints: ^4.0.0
  test: ^1.25.8
